### ISSUE TITLE
how to disable drag handler ?

### ISSUE THREAD

**Issue by athimannil** [heuristicmedia/bootstrap-slider-touch#1]
is there any option to disable handler. 

for example: when reach a particular value then stop drag something like that.

**Comment by irritant** [comment]
Not at this time. I'm open to pull requests if you implement your own solution.

**Comment by athimannil** [comment]
@irritant 
 I have made some changes on plugin now it works :) 

Can I implement ?

**Comment by irritant** [comment]
Please submit a pull request and Ill review it.
